"""
Initial database migration — creates all AgentCraft tables.

Generated by Alembic. This migration:
  1. Enables the pgvector extension
  2. Creates all 12 tables with indexes
  3. Uses UUID primary keys throughout
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY, INET, JSONB, UUID
from pgvector.sqlalchemy import Vector


revision = "001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Enable extensions
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "vector"')

    # ─── Organizations ─────────────────────────────────────────────────────────
    op.create_table(
        "organizations",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("slug", sa.String(100), nullable=False, unique=True),
        sa.Column("plan", sa.String(50), server_default="free"),
        sa.Column("settings", JSONB, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # ─── Users ────────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("org_id", UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("email", sa.String(255), unique=True, nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=True),
        sa.Column("full_name", sa.String(255), nullable=True),
        sa.Column("avatar_url", sa.Text, nullable=True),
        sa.Column("role", sa.String(50), server_default="member"),
        sa.Column("is_active", sa.Boolean, server_default="true"),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_users_email", "users", ["email"])
    op.create_index("ix_users_org_id", "users", ["org_id"])

    # ─── API Keys ─────────────────────────────────────────────────────────────
    op.create_table(
        "api_keys",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("org_id", UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("key_hash", sa.String(255), nullable=False),
        sa.Column("key_prefix", sa.String(10), nullable=False),
        sa.Column("scopes", ARRAY(sa.String), server_default="{}"),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # ─── Agents ───────────────────────────────────────────────────────────────
    op.create_table(
        "agents",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("org_id", UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("model_provider", sa.String(50), nullable=False, server_default="ollama"),
        sa.Column("model_name", sa.String(100), nullable=False, server_default="llama3.2"),
        sa.Column("temperature", sa.Float, server_default="0.7"),
        sa.Column("max_tokens", sa.Integer, server_default="4096"),
        sa.Column("top_p", sa.Float, server_default="1.0"),
        sa.Column("system_prompt", sa.Text, nullable=False),
        sa.Column("persona", sa.Text, nullable=True),
        sa.Column("instructions", JSONB, server_default="[]"),
        sa.Column("max_iterations", sa.Integer, server_default="25"),
        sa.Column("timeout_seconds", sa.Integer, server_default="300"),
        sa.Column("status", sa.String(50), server_default="draft"),
        sa.Column("version", sa.Integer, server_default="1"),
        sa.Column("tags", ARRAY(sa.String), server_default="{}"),
        sa.Column("metadata", JSONB, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_agents_org_id", "agents", ["org_id"])
    op.create_index("ix_agents_status", "agents", ["status"])

    # ─── Tools ────────────────────────────────────────────────────────────────
    op.create_table(
        "tools",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("org_id", UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text, nullable=False),
        sa.Column("category", sa.String(50), server_default="custom"),
        sa.Column("openapi_spec", JSONB, nullable=True),
        sa.Column("function_code", sa.Text, nullable=True),
        sa.Column("mcp_server_url", sa.Text, nullable=True),
        sa.Column("parameters_schema", JSONB, nullable=False, server_default="{}"),
        sa.Column("requires_approval", sa.Boolean, server_default="false"),
        sa.Column("sandbox_required", sa.Boolean, server_default="false"),
        sa.Column("timeout_seconds", sa.Integer, server_default="30"),
        sa.Column("is_active", sa.Boolean, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # ─── Agent Tools (junction) ───────────────────────────────────────────────
    op.create_table(
        "agent_tools",
        sa.Column("agent_id", UUID(as_uuid=True), sa.ForeignKey("agents.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("tool_id", UUID(as_uuid=True), sa.ForeignKey("tools.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("config_overrides", JSONB, server_default="{}"),
    )

    # ─── Workflows ────────────────────────────────────────────────────────────
    op.create_table(
        "workflows",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("org_id", UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("is_cyclic", sa.Boolean, server_default="false"),
        sa.Column("trigger_type", sa.String(50), server_default="manual"),
        sa.Column("trigger_config", JSONB, server_default="{}"),
        sa.Column("viewport", JSONB, server_default='{"x": 0, "y": 0, "zoom": 1}'),
        sa.Column("status", sa.String(50), server_default="draft"),
        sa.Column("version", sa.Integer, server_default="1"),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_workflows_org_id", "workflows", ["org_id"])

    # ─── Workflow Nodes ───────────────────────────────────────────────────────
    op.create_table(
        "workflow_nodes",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("workflow_id", UUID(as_uuid=True), sa.ForeignKey("workflows.id", ondelete="CASCADE"), nullable=False),
        sa.Column("node_key", sa.String(255), nullable=False),
        sa.Column("node_type", sa.String(50), nullable=False),
        sa.Column("label", sa.String(255), nullable=True),
        sa.Column("config", JSONB, server_default="{}"),
        sa.Column("position_x", sa.Float, server_default="0"),
        sa.Column("position_y", sa.Float, server_default="0"),
        sa.Column("width", sa.Float, nullable=True),
        sa.Column("height", sa.Float, nullable=True),
        sa.Column("metadata", JSONB, server_default="{}"),
        sa.UniqueConstraint("workflow_id", "node_key", name="uq_workflow_node_key"),
    )
    op.create_index("ix_workflow_nodes_workflow", "workflow_nodes", ["workflow_id"])

    # ─── Workflow Edges ───────────────────────────────────────────────────────
    op.create_table(
        "workflow_edges",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("workflow_id", UUID(as_uuid=True), sa.ForeignKey("workflows.id", ondelete="CASCADE"), nullable=False),
        sa.Column("source_node_id", UUID(as_uuid=True), sa.ForeignKey("workflow_nodes.id", ondelete="CASCADE"), nullable=False),
        sa.Column("target_node_id", UUID(as_uuid=True), sa.ForeignKey("workflow_nodes.id", ondelete="CASCADE"), nullable=False),
        sa.Column("edge_type", sa.String(50), server_default="default"),
        sa.Column("condition", JSONB, nullable=True),
        sa.Column("label", sa.String(255), nullable=True),
        sa.Column("priority", sa.Integer, server_default="0"),
        sa.Column("style", JSONB, server_default="{}"),
    )
    op.create_index("ix_workflow_edges_workflow", "workflow_edges", ["workflow_id"])
    op.create_index("ix_workflow_edges_source", "workflow_edges", ["source_node_id"])
    op.create_index("ix_workflow_edges_target", "workflow_edges", ["target_node_id"])

    # ─── Memories (pgvector) ──────────────────────────────────────────────────
    op.create_table(
        "memories",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("org_id", UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("agent_id", UUID(as_uuid=True), sa.ForeignKey("agents.id", ondelete="SET NULL"), nullable=True),
        sa.Column("memory_type", sa.String(50), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("summary", sa.Text, nullable=True),
        sa.Column("embedding", Vector(768), nullable=True),  # nomic-embed-text
        sa.Column("metadata", JSONB, server_default="{}"),
        sa.Column("tags", ARRAY(sa.String), server_default="{}"),
        sa.Column("importance", sa.Float, server_default="0.5"),
        sa.Column("access_count", sa.Integer, server_default="0"),
        sa.Column("last_accessed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    # Use raw SQL for the vector column and HNSW index (Alembic doesn't support it natively)
    op.execute("ALTER TABLE memories ALTER COLUMN embedding TYPE vector(768) USING NULL::vector(768)")
    op.execute("CREATE INDEX idx_memories_embedding ON memories USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)")
    op.create_index("ix_memories_agent_id", "memories", ["agent_id"])
    op.create_index("ix_memories_type", "memories", ["memory_type"])

    # ─── Runs ─────────────────────────────────────────────────────────────────
    op.create_table(
        "runs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("org_id", UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("workflow_id", UUID(as_uuid=True), sa.ForeignKey("workflows.id", ondelete="SET NULL"), nullable=True),
        sa.Column("triggered_by", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("status", sa.String(50), server_default="pending"),
        sa.Column("input_data", JSONB, server_default="{}"),
        sa.Column("output_data", JSONB, nullable=True),
        sa.Column("error", JSONB, nullable=True),
        sa.Column("total_steps", sa.Integer, server_default="0"),
        sa.Column("total_tokens_in", sa.Integer, server_default="0"),
        sa.Column("total_tokens_out", sa.Integer, server_default="0"),
        sa.Column("total_cost_usd", sa.Numeric(10, 6), server_default="0"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer, nullable=True),
        sa.Column("current_node_id", UUID(as_uuid=True), sa.ForeignKey("workflow_nodes.id"), nullable=True),
        sa.Column("checkpoint_state", JSONB, nullable=True),
        sa.Column("metadata", JSONB, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_runs_org_id", "runs", ["org_id"])
    op.create_index("ix_runs_workflow_id", "runs", ["workflow_id"])
    op.create_index("ix_runs_status", "runs", ["status"])

    # ─── Run Steps ────────────────────────────────────────────────────────────
    op.create_table(
        "run_steps",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("run_id", UUID(as_uuid=True), sa.ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("step_index", sa.Integer, nullable=False),
        sa.Column("node_id", UUID(as_uuid=True), sa.ForeignKey("workflow_nodes.id"), nullable=True),
        sa.Column("node_key", sa.String(255), nullable=True),
        sa.Column("step_type", sa.String(50), nullable=False),
        sa.Column("llm_request", JSONB, nullable=True),
        sa.Column("llm_response", JSONB, nullable=True),
        sa.Column("model_used", sa.String(100), nullable=True),
        sa.Column("tokens_in", sa.Integer, server_default="0"),
        sa.Column("tokens_out", sa.Integer, server_default="0"),
        sa.Column("cost_usd", sa.Numeric(10, 6), server_default="0"),
        sa.Column("tool_name", sa.String(255), nullable=True),
        sa.Column("tool_input", JSONB, nullable=True),
        sa.Column("tool_output", JSONB, nullable=True),
        sa.Column("state_before", JSONB, nullable=True),
        sa.Column("state_after", JSONB, nullable=True),
        sa.Column("state_delta", JSONB, nullable=True),
        sa.Column("memories_retrieved", JSONB, nullable=True),
        sa.Column("memories_stored", ARRAY(UUID(as_uuid=True)), server_default="{}"),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer, nullable=True),
        sa.Column("error", JSONB, nullable=True),
        sa.Column("metadata", JSONB, server_default="{}"),
    )
    op.create_index("ix_run_steps_run_id", "run_steps", ["run_id"])
    op.create_index("ix_run_steps_index", "run_steps", ["run_id", "step_index"])

    # ─── Run Checkpoints ──────────────────────────────────────────────────────
    op.create_table(
        "run_checkpoints",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("run_id", UUID(as_uuid=True), sa.ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("step_index", sa.Integer, nullable=False),
        sa.Column("state_snapshot", JSONB, nullable=False),
        sa.Column("reason", sa.String(50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_checkpoints_run_id", "run_checkpoints", ["run_id"])

    # ─── Secrets ──────────────────────────────────────────────────────────────
    op.create_table(
        "secrets",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("org_id", UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("encrypted_value", sa.Text, nullable=False),
        sa.Column("encryption_iv", sa.Text, nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("last_rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("org_id", "name", name="uq_secrets_org_name"),
    )

    # ─── Audit Logs ───────────────────────────────────────────────────────────
    op.create_table(
        "audit_logs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("org_id", UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("action", sa.String(100), nullable=False),
        sa.Column("resource_type", sa.String(50), nullable=True),
        sa.Column("resource_id", UUID(as_uuid=True), nullable=True),
        sa.Column("changes", JSONB, nullable=True),
        sa.Column("ip_address", sa.String(45), nullable=True),
        sa.Column("user_agent", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_audit_logs_org_id", "audit_logs", ["org_id"])
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"])


def downgrade() -> None:
    op.drop_table("audit_logs")
    op.drop_table("secrets")
    op.drop_table("run_checkpoints")
    op.drop_table("run_steps")
    op.drop_table("runs")
    op.drop_table("memories")
    op.drop_table("workflow_edges")
    op.drop_table("workflow_nodes")
    op.drop_table("workflows")
    op.drop_table("agent_tools")
    op.drop_table("tools")
    op.drop_table("agents")
    op.drop_table("api_keys")
    op.drop_table("users")
    op.drop_table("organizations")
    op.execute('DROP EXTENSION IF EXISTS "vector"')
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp"')
